version: '3'
services:
  atomic-agents:
    build:
      context: ../
      dockerfile: docker/torch2.0.1_cuda11.7.dockerfile
    image: atomic-agents:0.0.1
    runtime: nvidia
    container_name: atomic-agents
    tty: true
    restart: always
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 40G
    volumes:
      - /home/zhangjl19/:/workspace
    networks:
      - test-net
      
networks:
  test-net:
    external: true